# Generated by Django 2.2 on 2019-12-14 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pics', verbose_name='Фотография')),
                ('label', models.CharField(max_length=2000, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_picture', to='webapp.Photo', verbose_name='Фотография')),
            ],
        ),
    ]
