# Generated by Django 2.2 on 2019-12-14 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_owner',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайк поставил'),
        ),
    ]
