# Generated by Django 2.2 on 2019-12-14 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_photo_like_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='like_owner',
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_like_owner', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин лайка')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_liked', to='webapp.Photo', verbose_name='Понравившаяся')),
            ],
        ),
    ]
